### PR TITLE
added placeholder in api

### PR DESCRIPTION
**Pull request by timmy-cde**
fixed placeholder bug in the api

### CODE REVIEW

**Comment by ghost** [comment]
On it! I'll review the changes as soon as possible!

**Review by ghost — CHANGES_REQUESTED** [review]
I don't think it'll work. Make sure it passes all checks, and  only then you'll be able to merge the PR.

**Comment by timmy-cde** [comment]
fixed placeholder in the api again

**Review by ghost — APPROVED** [review]
Perfect Timothy! You're now able to merge the PR.

**Pull request merged**
